application: natural-num
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: (.*\.(html|css|js))
  
- url: /(.*\.(html|css|js|txt))
  static_files: \1
  upload: (.*\.(html|css|js|txt))
  
- url: /nnjson.py
  script: nnjson.py